export const GOVERNORATES = [
  { key: 'cairo', name: 'Cairo' },
  { key: 'giza', name: 'Giza' },
  { key: 'qalyubia', name: 'Qalyubia' },
  { key: 'alexandria', name: 'Alexandria' },
  { key: 'beheira', name: 'Beheira' },
  { key: 'gharbia', name: 'Gharbia' },
  { key: 'sharqia', name: 'Sharqia' },
  { key: 'dakahlia', name: 'Dakahlia' },
  { key: 'damietta', name: 'Damietta' },
  { key: 'monufia', name: 'Monufia' },
  { key: 'kafr_el_sheikh', name: 'Kafr El Sheikh' },
  { key: 'port_said', name: 'Port Said' },
  { key: 'ismailia', name: 'Ismailia' },
  { key: 'suez', name: 'Suez' },
  { key: 'fayoum', name: 'Fayoum' },
  { key: 'beni_suef', name: 'Beni Suef' },
  { key: 'minya', name: 'Minya' },
  { key: 'assiut', name: 'Assiut' },
  { key: 'sohag', name: 'Sohag' },
  { key: 'qena', name: 'Qena' },
  { key: 'luxor', name: 'Luxor' },
  { key: 'aswan', name: 'Aswan' },
  { key: 'matrouh', name: 'Matrouh' },
  { key: 'red_sea', name: 'Red Sea' },
  { key: 'south_sinai', name: 'South Sinai' },
  { key: 'north_sinai', name: 'North Sinai' },
  { key: 'new_valley', name: 'New Valley' },
]
